kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-opendata
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  type: gp2
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: opendata-pv-dags
spec:
  volumeMode: Filesystem
  storageClassName: local-opendata
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
     namespace: opendata
     name: pvc-opendata-dags
  hostPath:
    path: "/airflow-dags"


---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: airflow
    release: openmetadata-dependencies
  name: pvc-opendata-dags
  namespace: opendata
spec:
  storageClassName: local-opendata
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi